title: ML at University of Arizona
email: cscheid@cs.arizona.edu
description: A website collecting information and resources about machine learning at UA.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ml.arizona.edu" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
